name: umiuni2d
version: 0.0.2
description: A starting point for Dart libraries or applications.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  flutter:
    path: /Users/kyorohiro/tools/git/flutter/packages/flutter
  vector_math: any
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
